### ISSUE TITLE
Installing via npm command

### ISSUE THREAD

**Issue by Novirius** [cristovao-trevisan/pitchfinder#2]
I'm running into the following error while running `npm i node-pitchfinder`
```../src/detectors/yin/addon/yin.cc: In static member function ‘static void Yin::Init(v8::Local<v8::Object>)’:
../src/detectors/yin/addon/yin.cc:17:38: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   constructor.Reset(tpl->GetFunction());
                                      ^
In file included from /home/novirius/.cache/node-gyp/13.3.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/detectors/yin/addon/yin.cc:1:
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:6283:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:6283:46: note:   candidate expects 1 argument, 0 provided
../src/detectors/yin/addon/yin.cc:18:67: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   exports->Set(Nan::New("Yin").ToLocalChecked(), tpl->GetFunction());
                                                                   ^
In file included from /home/novirius/.cache/node-gyp/13.3.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/detectors/yin/addon/yin.cc:1:
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:6283:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:6283:46: note:   candidate expects 1 argument, 0 provided
../src/detectors/yin/addon/yin.cc: In static member function ‘static void Yin::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/detectors/yin/addon/yin.cc:22:95: error: no matching function for call to ‘v8::Value::NumberValue()’
   double sampleRate = info[0]->IsUndefined() ? DEFAULT_YIN_SAMPLE_RATE : info[0]->NumberValue();
                                                                                               ^
In file included from /home/novirius/.cache/node-gyp/13.3.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/detectors/yin/addon/yin.cc:1:
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:2773:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:2773:39: note:   candidate expects 1 argument, 0 provided
../src/detectors/yin/addon/yin.cc:23:92: error: no matching function for call to ‘v8::Value::NumberValue()’
   double threshold = info[1]->IsUndefined() ? DEFAULT_YIN_THRESHOLD : info[1]->NumberValue();
                                                                                            ^
In file included from /home/novirius/.cache/node-gyp/13.3.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/detectors/yin/addon/yin.cc:1:
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:2773:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:2773:39: note:   candidate expects 1 argument, 0 provided
../src/detectors/yin/addon/yin.cc:24:115: error: no matching function for call to ‘v8::Value::NumberValue()’
   double probabilityThreshold = info[2]->IsUndefined() ? DEFAULT_YIN_PROBABILITY_THRESHOLD : info[2]->NumberValue();
                                                                                                                   ^
In file included from /home/novirius/.cache/node-gyp/13.3.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/detectors/yin/addon/yin.cc:1:
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:2773:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^~~~~~~~~~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:2773:39: note:   candidate expects 1 argument, 0 provided
../src/detectors/yin/addon/yin.cc: In static member function ‘static void Yin::getResult(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/detectors/yin/addon/yin.cc:61:66: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Number>::return_t 
’
   result->Set(Nan::New("pitch").ToLocalChecked(), Nan::New(pitch));
                                                                  ^
In file included from /home/novirius/.cache/node-gyp/13.3.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/detectors/yin/addon/yin.cc:1:
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../src/detectors/yin/addon/yin.cc:62:83: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Number>::return_t 
’
   result->Set(Nan::New("probability").ToLocalChecked(), Nan::New(obj->probability));
                                                                                   ^
In file included from /home/novirius/.cache/node-gyp/13.3.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from ../src/detectors/yin/addon/yin.cc:1:
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:3547:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:3550:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/home/novirius/.cache/node-gyp/13.3.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
addon.target.mk:111: recipe for target 'Release/obj.target/addon/src/detectors/yin/addon/yin.o' failed
make: *** [Release/obj.target/addon/src/detectors/yin/addon/yin.o] Error 1
make: Leaving directory '/mnt/c/Users/absol/Documents/aaProjects/keyboardwarrior/node_modules/node-pitchfinder/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/novirius/.nvm/versions/node/v13.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Linux 4.4.0-19041-Microsoft
gyp ERR! command "/home/novirius/.nvm/versions/node/v13.3.0/bin/node" "/home/novirius/.nvm/versions/node/v13.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/c/Users/absol/Documents/aaProjects/keyboardwarrior/node_modules/node-pitchfinder
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN keyboardwarrior@1.0.0 No description
npm WARN keyboardwarrior@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pitchfinder@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pitchfinder@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by cristovao-trevisan** [comment]
Can you try it using a node version <=10 ??
It's been some time since I've used this library, so that is probably the issue at place.
I'm full these days, so it may take some weeks for me to have a look at this. Would appreciate if you can check this by yourself :)
